export default [
  {
    _id: "A101",
    title: "Propulsion Assignment",
    course: "RS101",
    not_available_until: "2024-05-06T00:01",
    due: "2024-05-13T23:59",
    points: "100",
    submissionType: "Online",
    displayGradeAs: "Percentage",
    assignTo: "Tony Stark",
    assignmentGroup: "ASSIGNMENTS",
    description:
      "The assignment is available online Submit a link to the landing page of your web application",
  },
  {
    _id: "A102",
    title: "Combustion Analysis",
    course: "RS101",
    not_available_until: "2024-05-13T00:01",
    due: "2024-05-20T23:59",
    points: "100",
    submissionType: "Online",
    displayGradeAs: "Percentage",
    assignTo: "Everyone",
    assignmentGroup: "ASSIGNMENTS",
    description:
      "The assignment is available online Submit a link to the landing page of your web application",
  },
  {
    _id: "A103",
    title: "Nozzle Design Project",
    course: "RS101",
    not_available_until: "2024-05-20T00:01",
    due: "2024-05-27T23:59",
    points: "100",
    submissionType: "External Tool",
    displayGradeAs: "Letter",
    assignTo: "Everyone",
    assignmentGroup: "ASSIGNMENTS",
    description:
      "The assignment is available online Submit a link to the landing page of your web application",
  },
  {
    _id: "A201",
    title: "Aerodynamics Quiz",
    course: "RS102",
    not_available_until: "2024-05-06T00:01",
    due: "2024-05-13T23:59",
    points: "100",
    submissionType: "Online",
    displayGradeAs: "Percentage",
    assignTo: "Everyone",
    assignmentGroup: "QUIZZES",
    description:
      "The assignment is available online Submit a link to the landing page of your web application",
  },
  {
    _id: "A202",
    title: "Flow Analysis",
    course: "RS102",
    not_available_until: "2024-05-13T00:01",
    due: "2024-05-20T23:59",
    points: "100",
    submissionType: "Online",
    displayGradeAs: "Percentage",
    assignTo: "Everyone",
    assignmentGroup: "ASSIGNMENTS",
    description:
      "The assignment is available online Submit a link to the landing page of your web application",
  },
  {
    _id: "A203",
    title: "Heating Analysis",
    course: "RS102",
    not_available_until: "2024-05-20T00:01",
    due: "2024-05-27T23:59",
    points: "100",
    submissionType: "Online",
    displayGradeAs: "Percentage",
    assignTo: "Everyone",
    assignmentGroup: "ASSIGNMENTS",
    description:
      "The assignment is available online Submit a link to the landing page of your web application",
  },
  {
    _id: "A301",
    title: "Structural Design Task",
    course: "RS103",
    not_available_until: "2024-05-06T00:01",
    due: "2024-05-13T23:59",
    points: "100",
    submissionType: "Online",
    displayGradeAs: "Percentage",
    assignTo: "Everyone",
    assignmentGroup: "ASSIGNMENTS",
    description:
      "The assignment is available online Submit a link to the landing page of your web application",
  },
  {
    _id: "A302",
    title: "Orbital Calculations",
    course: "RS103",
    not_available_until: "2024-05-13T00:01",
    due: "2024-05-20T23:59",
    points: "100",
    submissionType: "Online",
    displayGradeAs: "Percentage",
    assignTo: "Everyone",
    assignmentGroup: "ASSIGNMENTS",
    description:
      "The assignment is available online Submit a link to the landing page of your web application",
  },
  {
    _id: "A303",
    title: "Systems Engineering Exam",
    course: "RS103",
    not_available_until: "2024-05-20T00:01",
    due: "2024-05-27T23:59",
    points: "100",
    submissionType: "No Submission",
    displayGradeAs: "Percentage",
    assignTo: "Everyone",
    assignmentGroup: "EXAMS",
    description:
      "The assignment is available online Submit a link to the landing page of your web application",
  },
];
